#!/bin/sh

current_branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$current_branch" = "main" ] || [ "$current_branch" = "staging" ]; then
  echo "Direct push to protected branch ($current_branch) is not allowed. Open a PR." >&2
  exit 1
fi

exit 0
