#!/bin/sh

current_branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$current_branch" = "main" ] || [ "$current_branch" = "staging" ]; then
  cat <<EOF
Direct push to protected branch is not allowed.

Protected branch:
$current_branch

Please create a new branch and open a Pull Request instead.

Recommended flow:
feature/your-task -> dev -> staging -> main

Allowed branch examples:
feature/add-product-search
bugfix/fix-cart-price
hotfix/payment-timeout
chore/update-dependencies
EOF
  exit 1
fi

exit 0
