package com.lssgoo.core.presentation.theme

import androidx.compose.ui.graphics.Color

/**
 * The five palettes the web frontend ships. Hex values are copied verbatim from
 * `frontend-web/src/theme/palettes.ts`. When the web team rotates a color, mirror
 * the change here so brand experience stays consistent across surfaces.
 */
object Palettes {

    val ForestTrail = Palette(
        id = PaletteId.ForestTrail,
        displayName = "Forest Trail",
        light = PaletteTokens(
            background = Color(0xFFF7F8F4),
            card = Color(0xFFFFFFFF),
            popover = Color(0xFFFFFFFF),
            muted = Color(0xFFEDF0E7),
            border = Color(0xFFDDE2D2),
            input = Color(0xFFEDF0E7),
            ring = Color(0xFF2F855A),
            foreground = Color(0xFF1A2E22),
            cardForeground = Color(0xFF1A2E22),
            popoverForeground = Color(0xFF1A2E22),
            mutedForeground = Color(0xFF5C6B5E),
            primary = Color(0xFF2F855A),
            primaryForeground = Color(0xFFFFFFFF),
            secondary = Color(0xFFE2E8DC),
            secondaryForeground = Color(0xFF1A2E22),
            accent = Color(0xFF84A98C),
            accentForeground = Color(0xFF1A2E22),
            success = Color(0xFF22C55E),
            successForeground = Color(0xFFFFFFFF),
            destructive = Color(0xFFDC2626),
            destructiveForeground = Color(0xFFFFFFFF),
        ),
        dark = PaletteTokens(
            background = Color(0xFF0E1410),
            card = Color(0xFF161D18),
            popover = Color(0xFF161D18),
            muted = Color(0xFF1F2823),
            border = Color(0xFF2A332D),
            input = Color(0xFF1F2823),
            ring = Color(0xFF48BB78),
            foreground = Color(0xFFE6EBE3),
            cardForeground = Color(0xFFE6EBE3),
            popoverForeground = Color(0xFFE6EBE3),
            mutedForeground = Color(0xFF9BAA9B),
            primary = Color(0xFF48BB78),
            primaryForeground = Color(0xFF0E1410),
            secondary = Color(0xFF243029),
            secondaryForeground = Color(0xFFE6EBE3),
            accent = Color(0xFF84A98C),
            accentForeground = Color(0xFF0E1410),
            success = Color(0xFF22C55E),
            successForeground = Color(0xFFE6EBE3),
            destructive = Color(0xFFF87171),
            destructiveForeground = Color(0xFF0E1410),
        ),
    )

    val SunsetHorizon = Palette(
        id = PaletteId.SunsetHorizon,
        displayName = "Sunset Horizon",
        light = PaletteTokens(
            background = Color(0xFFFFF8F1),
            card = Color(0xFFFFFFFF),
            popover = Color(0xFFFFFFFF),
            muted = Color(0xFFFCEEDF),
            border = Color(0xFFF4DDBF),
            input = Color(0xFFFCEEDF),
            ring = Color(0xFFE85D3C),
            foreground = Color(0xFF2A1810),
            cardForeground = Color(0xFF2A1810),
            popoverForeground = Color(0xFF2A1810),
            mutedForeground = Color(0xFF7A5746),
            primary = Color(0xFFE85D3C),
            primaryForeground = Color(0xFFFFFFFF),
            secondary = Color(0xFFFBE2CB),
            secondaryForeground = Color(0xFF2A1810),
            accent = Color(0xFFF4B860),
            accentForeground = Color(0xFF2A1810),
            success = Color(0xFF22C55E),
            successForeground = Color(0xFFFFFFFF),
            destructive = Color(0xFFDC2626),
            destructiveForeground = Color(0xFFFFFFFF),
        ),
        dark = PaletteTokens(
            background = Color(0xFF1A0F08),
            card = Color(0xFF24160D),
            popover = Color(0xFF24160D),
            muted = Color(0xFF2E1D11),
            border = Color(0xFF3A2615),
            input = Color(0xFF2E1D11),
            ring = Color(0xFFFF7B5A),
            foreground = Color(0xFFF4E3D2),
            cardForeground = Color(0xFFF4E3D2),
            popoverForeground = Color(0xFFF4E3D2),
            mutedForeground = Color(0xFFB7967E),
            primary = Color(0xFFFF7B5A),
            primaryForeground = Color(0xFF1A0F08),
            secondary = Color(0xFF35200F),
            secondaryForeground = Color(0xFFF4E3D2),
            accent = Color(0xFFF4B860),
            accentForeground = Color(0xFF1A0F08),
            success = Color(0xFF22C55E),
            successForeground = Color(0xFFF4E3D2),
            destructive = Color(0xFFF87171),
            destructiveForeground = Color(0xFF1A0F08),
        ),
    )

    val TropicalParadise = Palette(
        id = PaletteId.TropicalParadise,
        displayName = "Tropical Paradise",
        light = PaletteTokens(
            background = Color(0xFFF0FDFC),
            card = Color(0xFFFFFFFF),
            popover = Color(0xFFFFFFFF),
            muted = Color(0xFFDDFAF6),
            border = Color(0xFFB7EEE8),
            input = Color(0xFFDDFAF6),
            ring = Color(0xFF0D9488),
            foreground = Color(0xFF0E2A28),
            cardForeground = Color(0xFF0E2A28),
            popoverForeground = Color(0xFF0E2A28),
            mutedForeground = Color(0xFF4F7A77),
            primary = Color(0xFF0D9488),
            primaryForeground = Color(0xFFFFFFFF),
            secondary = Color(0xFFC8F0EB),
            secondaryForeground = Color(0xFF0E2A28),
            accent = Color(0xFFFACC15),
            accentForeground = Color(0xFF0E2A28),
            success = Color(0xFF14B8A6),
            successForeground = Color(0xFFFFFFFF),
            destructive = Color(0xFFDC2626),
            destructiveForeground = Color(0xFFFFFFFF),
        ),
        dark = PaletteTokens(
            background = Color(0xFF0B1F1E),
            card = Color(0xFF132B29),
            popover = Color(0xFF132B29),
            muted = Color(0xFF1A3735),
            border = Color(0xFF234542),
            input = Color(0xFF1A3735),
            ring = Color(0xFF2DD4BF),
            foreground = Color(0xFFD9F2EF),
            cardForeground = Color(0xFFD9F2EF),
            popoverForeground = Color(0xFFD9F2EF),
            mutedForeground = Color(0xFF85B0AC),
            primary = Color(0xFF2DD4BF),
            primaryForeground = Color(0xFF0B1F1E),
            secondary = Color(0xFF1E3F3C),
            secondaryForeground = Color(0xFFD9F2EF),
            accent = Color(0xFFFACC15),
            accentForeground = Color(0xFF0B1F1E),
            success = Color(0xFF14B8A6),
            successForeground = Color(0xFFD9F2EF),
            destructive = Color(0xFFF87171),
            destructiveForeground = Color(0xFF0B1F1E),
        ),
    )

    val MountainMist = Palette(
        id = PaletteId.MountainMist,
        displayName = "Mountain Mist",
        light = PaletteTokens(
            background = Color(0xFFF8FAFB),
            card = Color(0xFFFFFFFF),
            popover = Color(0xFFFFFFFF),
            muted = Color(0xFFEEF1F4),
            border = Color(0xFFD9DEE5),
            input = Color(0xFFEEF1F4),
            ring = Color(0xFF475569),
            foreground = Color(0xFF1B202B),
            cardForeground = Color(0xFF1B202B),
            popoverForeground = Color(0xFF1B202B),
            mutedForeground = Color(0xFF66707D),
            primary = Color(0xFF475569),
            primaryForeground = Color(0xFFFFFFFF),
            secondary = Color(0xFFE0E5EC),
            secondaryForeground = Color(0xFF1B202B),
            accent = Color(0xFF84CC8C),
            accentForeground = Color(0xFF1B202B),
            success = Color(0xFF22C55E),
            successForeground = Color(0xFFFFFFFF),
            destructive = Color(0xFFDC2626),
            destructiveForeground = Color(0xFFFFFFFF),
        ),
        dark = PaletteTokens(
            background = Color(0xFF0D1117),
            card = Color(0xFF161B22),
            popover = Color(0xFF161B22),
            muted = Color(0xFF1F242C),
            border = Color(0xFF2A2F38),
            input = Color(0xFF1F242C),
            ring = Color(0xFF94A3B8),
            foreground = Color(0xFFE6EAF0),
            cardForeground = Color(0xFFE6EAF0),
            popoverForeground = Color(0xFFE6EAF0),
            mutedForeground = Color(0xFF9CA8B8),
            primary = Color(0xFF94A3B8),
            primaryForeground = Color(0xFF0D1117),
            secondary = Color(0xFF252B33),
            secondaryForeground = Color(0xFFE6EAF0),
            accent = Color(0xFF84CC8C),
            accentForeground = Color(0xFF0D1117),
            success = Color(0xFF22C55E),
            successForeground = Color(0xFFE6EAF0),
            destructive = Color(0xFFF87171),
            destructiveForeground = Color(0xFF0D1117),
        ),
    )

    val DesertDunes = Palette(
        id = PaletteId.DesertDunes,
        displayName = "Desert Dunes",
        light = PaletteTokens(
            background = Color(0xFFFBF6EE),
            card = Color(0xFFFFFFFF),
            popover = Color(0xFFFFFFFF),
            muted = Color(0xFFF3E8D4),
            border = Color(0xFFE4D2B3),
            input = Color(0xFFF3E8D4),
            ring = Color(0xFFB45309),
            foreground = Color(0xFF2A1C0A),
            cardForeground = Color(0xFF2A1C0A),
            popoverForeground = Color(0xFF2A1C0A),
            mutedForeground = Color(0xFF7C6440),
            primary = Color(0xFFB45309),
            primaryForeground = Color(0xFFFFFFFF),
            secondary = Color(0xFFEDD9B0),
            secondaryForeground = Color(0xFF2A1C0A),
            accent = Color(0xFFD4A04C),
            accentForeground = Color(0xFF2A1C0A),
            success = Color(0xFF22C55E),
            successForeground = Color(0xFFFFFFFF),
            destructive = Color(0xFFDC2626),
            destructiveForeground = Color(0xFFFFFFFF),
        ),
        dark = PaletteTokens(
            background = Color(0xFF1B130B),
            card = Color(0xFF251A0F),
            popover = Color(0xFF251A0F),
            muted = Color(0xFF2F2113),
            border = Color(0xFF3D2C1A),
            input = Color(0xFF2F2113),
            ring = Color(0xFFF59E0B),
            foreground = Color(0xFFF1E3CB),
            cardForeground = Color(0xFFF1E3CB),
            popoverForeground = Color(0xFFF1E3CB),
            mutedForeground = Color(0xFFC0A878),
            primary = Color(0xFFF59E0B),
            primaryForeground = Color(0xFF1B130B),
            secondary = Color(0xFF382712),
            secondaryForeground = Color(0xFFF1E3CB),
            accent = Color(0xFFD4A04C),
            accentForeground = Color(0xFF1B130B),
            success = Color(0xFF22C55E),
            successForeground = Color(0xFFF1E3CB),
            destructive = Color(0xFFF87171),
            destructiveForeground = Color(0xFF1B130B),
        ),
    )

    val all: List<Palette> = listOf(
        ForestTrail, SunsetHorizon, TropicalParadise, MountainMist, DesertDunes,
    )

    val default: Palette = ForestTrail

    fun byId(id: PaletteId): Palette = all.first { it.id == id }
}
